menu:
  主页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  # Tags: /tags/ || fas fa-tags
  文章分类: /categories/ || fas fa-folder-open
  # List||fas fa-list:
  #   Music: /music/ || fas fa-music
  #   Movie: /movies/ || fas fa-video
  # Link: /link/ || fas fa-link
  About: /about/ || fas fa-heart

# Code Blocks (代碼相關)
# --------------------------------------

highlight_theme: mac #  darker / pale night / light / ocean / mac / mac light / false
highlight_copy: true # copy button
highlight_lang: true # show the code language
highlight_shrink: false # true: shrink the code blocks / false: expand the code blocks | none: expand code blocks and hide the button
highlight_height_limit: 200 # unit: px
code_word_wrap: false

# 社交
social:
  fab fa-github: https://github.com/jackerzz || Github
  # fas fa-envelope: miningrest1024@gmail.com || Email

# 顶部图
# Favicon（網站圖標）
favicon: https://cdn.jsdelivr.net/gh/jackerzz/jackerzz.github.io@sion1.0/images/img/bookgirl_ico.jpg
# Avatar (頭像)
avatar:
  img: https://cdn.jsdelivr.net/gh/jackerzz/jackerzz.github.io@sion1.0/images/avatar/35586448.jpg
  effect: false

# 主页的横幅图像

background: url(https://cdn.jsdelivr.net/gh/jackerzz/jackerzz.github.io@sion1.0/images/img/光芒万丈的未来.jpg)

# The banner image of home page
index_img: 'linear-gradient(20deg, #0062be, #925696, #cc426e, #fb0347)'
default_top_img: https://cdn.jsdelivr.net/gh/jackerzz/jackerzz.github.io@sion1.0/images/img/魔法森.jpg
archive_img: http://static.kongdf.com/banner.jpg
tag_img: http://static.kongdf.com/banner.jpg
category_img: https://cdn.jsdelivr.net/gh/jackerzz/jackerzz.github.io@sion1.0/images/img/yasoga no sora.jpg

cover:
  # display the cover or not (是否顯示文章封面)
  index_enable: true
  aside_enable: true
  archives_enable: true
  # the position of cover in home page (封面顯示的位置)
  # left/right/both
  position: both
  # When cover is not set, the default cover is displayed (當沒有設置cover時，默認的封面顯示)
  default_cover:
    - https://cdn.jsdelivr.net/gh/jackerzz/jackerzz.github.io@ersion1.1/images/canva/531767.jpg
    - https://cdn.jsdelivr.net/gh/jackerzz/jackerzz.github.io@ersion1.1/images/canva/615299.jpg
    - https://cdn.jsdelivr.net/gh/jackerzz/jackerzz.github.io@ersion1.1/images/canva/777211.jpg
    - https://cdn.jsdelivr.net/gh/jackerzz/jackerzz.github.io@ersion1.1/images/canva/1142950.jpg
    - https://cdn.jsdelivr.net/gh/jackerzz/jackerzz.github.io@ersion1.1/images/canva/1376766.jpg
    - https://cdn.jsdelivr.net/gh/jackerzz/jackerzz.github.io@ersion1.1/images/canva/1553463.jpg
    - https://cdn.jsdelivr.net/gh/jackerzz/jackerzz.github.io@ersion1.1/images/canva/1819651.jpg
    - https://cdn.jsdelivr.net/gh/jackerzz/jackerzz.github.io@ersion1.1/images/canva/2347011.jpg
    - https://cdn.jsdelivr.net/gh/jackerzz/jackerzz.github.io@ersion1.1/images/canva/2579916.jpg
    - https://cdn.jsdelivr.net/gh/jackerzz/jackerzz.github.io@ersion1.1/images/canva/2753432.jpg
    - https://cdn.jsdelivr.net/gh/jackerzz/jackerzz.github.io@ersion1.1/images/canva/3225517.jpg
    - https://cdn.jsdelivr.net/gh/jackerzz/jackerzz.github.io@ersion1.1/images/canva/3244513.jpg
    - https://cdn.jsdelivr.net/gh/jackerzz/jackerzz.github.io@ersion1.1/images/canva/3408744.jpg
    - https://cdn.jsdelivr.net/gh/jackerzz/jackerzz.github.io@ersion1.1/images/canva/3560044.jpg
    - https://cdn.jsdelivr.net/gh/jackerzz/jackerzz.github.io@ersion1.1/images/canva/4751187.jpg


    
# Replace Broken Images (替換無法顯示的圖片)
error_img:
  flink: /img/friend_404.gif
  post_page: http://static.kongdf.com/bg4.jpg
# Share System (分享功能)
# --------------------------------------

# AddThis
# https://www.addthis.com/
addThis:
  enable: false
  pubid:

# Share.js
# https://github.com/overtrue/share.js
sharejs:
  enable: true
  sites: wechat,weibo,qq

# AddToAny
# https://www.addtoany.com/
addtoany:
  enable: false
  item: wechat,email,copy_link

theme_color:
  enable: true
  main: "#49B1F5"
#   paginator: "#00c4b6"
  button_hover: "#1979a6"

# Mouse click effects: words (鼠標點擊效果: 文字)
ClickShowText:
  enable: true
  text:
     - IU
     - iu
  fontSize: 15px
  random: false
  mobile: false

# Conversion between Traditional and Simplified Chinese (簡繁轉換)
translate:
  enable: false
  # The text of a button
  default: 簡
  # the language of website (1 - Traditional Chinese/ 2 - Simplified Chinese）
  defaultEncoding: 2
  # Time delay
  translateDelay: 0
  # The text of the button when the language is Simplified Chinese
  msgToTraditionalChinese: '繁'
  # The text of the button when the language is Traditional Chinese
  
  msgToSimplifiedChinese: '簡'

# aside (側邊欄)
# --------------------------------------

aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: right # left or right
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/jackerzz
  card_announcement:
    enable: true
    content: This is my Blog
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
    sort_order: # Don't modify the setting unless you know how it works
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: false
    sort_order: # Don't modify the setting unless you know how it works
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: # Don't modify the setting unless you know how it works
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: # Don't modify the setting unless you know how it works

# https://github.com/vinta/pangu.js
# Insert a space between Chinese character and English character (中英文之間添加空格)
pangu:
  enable: true
  field: site # site/post

# https://instant.page/
# prefetch (預加載)
instantpage: true

# Lazyload (圖片懶加載)
# https://github.com/verlok/vanilla-lazyload
lazyload:
  enable: true
  field: site # site/post
  placeholder:
  blur: true